spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres

jpa properties:
    hibernate:
      show_sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        default_schema: public


    flyway:
      baseline-on-migrate: true
      locations: classpath:src/main/resources/db/migration

      create-schemas: false
      init-sqls: CREATE IF NOT EXISTS flyway_history_schema
      schemas: flyway_history_schema,public
      user: postgres
      password: postgres
      default-schema: public