version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-container-message
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5434:5432"

  postgres-userchat:
    image: postgres
    container_name: postgres-container-userchat
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"