spring:
  jpa:
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        default_schema: public



  flyway:
    baseline-on-migrate: true
    locations: classpath:src/main/resources/db/migration

    create-schemas: false
    init-sqls: CREATE IF NOT EXISTS flyway_history_schema
    schemas: flyway_history_schema,public
    user: postgres
    password: mysecretpassword
    default-schema: public

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      userchats:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
        minimumNumberOfCalls: 5
#        waitDurationInOpenState: 5s
#        failureRateThreshold: 50
#        slowCallRateThreshold: 100
        slowCallDurationThreshold: 1500ms
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        recordExceptions:
#            - java.lang.RuntimeException
#        properties for this service calls
