debug: false
server:
  port: 8150
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        default_schema: public


  flyway:
    baseline-on-migrate: true
    locations: classpath:src/main/resources/db/migration

    create-schemas: false
    init-sqls: CREATE IF NOT EXISTS flyway_history_schema
    schemas: flyway_history_schema,public
    user: postgres
    password: postgres
    default-schema: public

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 815781859442-muc5qasn0mnnf5vlgfm0b3eotro4n9ce.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

gcp:
  vars:
    admin.user: ${ADMIN_USERNAME:test@gmail.com}
    admin.password: ${ADMIN_PASSWORD:12345}


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
