server:
  port: 8888

spring:
  application:
    name: userchats
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VikMoto/chaticoconf.git
          username: ig.basalt@gmail.com
          password: Ti&KE-592gHu
#        native:
#          search-locations:
#          - classpath:/config
#          - classpath:/config/userchats.yml
#          search-locations: file:///E:/HOME/chatico/config-service/src/main/resources/config/userchats.yml

#vault:
# sha256:b2177a8bfe85f89ff403c9f51b8a00a6efd1be8e475bc2637390c36977df994d
